import comidas.*
import wollok.game.*

object pepona {

	method image() {
		return "pepona.png"
	}

	method position() {
		// TODO: Autogenerated Code ! 
		return game.at(-1, -1)
	}

	method persegui(alguien) {
	// TODO: Autogenerated Code ! 
	}

	method darPremio() {
	// TODO: Autogenerated Code ! 
	}

}

